version: "3.8"

services:
  space-flight-light:
    container_name: space-flight-news
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev --host
